# Generated by Django 4.1 on 2022-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='rating',
            field=models.FloatField(default=4.5, null=True),
        ),
    ]
